### ISSUE TITLE
Wrapper does not allow compiling with win32

### ISSUE THREAD

**Issue by swashdev** [unleashy/pdcurses-d#1]
Trying to use this wrapper to compile a Windows program with PDCurses produces the following error message:

`LINK : fatal error LNK1181: cannot open input file 'pdcurses.lib'`

`Error: C:\Program Files\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.15.26726\bin\HostX86\x86\link.exe failed with status: 1181`

As you can see, the error occurs when attempting to compile with MSVC 2017 on win32.

I'm not certain whether this is a problem with the wrapper or with the PDCurses library itself, because I'm not familiar enough with the source code for PDCurses, let alone the Windows-specific build thereof.  In any case, no further updates to the PDCurses code base have been made since I compiled my library files.

The same source code appears to work fine with ncurses, and a friend has told me that it compiles fine with PDCurses on Linux, but it still fails on Windows.

**Comment by unleashy** [comment]
You need pdcurses.lib somewhere in the paths defined in your `LIB` environment variable. For me, LIB is this:
```
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\ATLMFC\lib\x86;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\lib\x86;C:\Program Files (x86)\Windows Kits\10\lib\10.0.16299.0\ucrt\x86;C:\Program Files (x86)\Windows Kits\10\lib\10.0.16299.0\um\x86;
```

**Comment by swashdev** [comment]
Thank you very much.  This got my program to compile, at least.  It's still crashing, but I suppose that's a mystery I'll just have to resolve elsewhere.
